### ISSUE TITLE
Fix readme with all Lambda World projects

### ISSUE THREAD

**Issue by jvican** [scalacenter/sprees#37]
There have been some changes that I merged and make the README a little bit inconsistent, since it mixes details from both Scala IO and Lambda World.
  
Tomorrow morning I will work on adding only Lambda World details and putting all Scala io spree details in another document, with a link to it from the README. @julienrf 
  
/cc @Duhemm Any chance we can add scala-native to the project list? It would be awesome to have some spree tickets there.

**Comment by Duhemm** [comment]
@jvican Yes, the issues are ready, I just need to open the actual tickets. I'll do that ASAP.

**Comment by jvican** [comment]
I've updated the README. Do it on top of latest master @Duhemm :smile:. Closing.
