### ISSUE TITLE
Add guidelines on how to add projects to a hackathon

### ISSUE THREAD

**Issue by jvican** [scalacenter/sprees#7]
Write small document explaining:
  
* Organization of the hackathon. Duration, pace, steps.
* Steps to add a project to a Scala Center hackathon.
* Suggestions on how to be a good maintainer.
* Suggestions on how to write good issues.
* Suggestions on how to guide first-time contributors.
  
I will use my experience running hackathons to write those guidelines.

**Comment by heathermiller** [comment]
Pity that this still isn't done yet.
